server:
  port: 8080
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/search_engine
    username: postgres
    password: 27030176

# example values

indexing-settings:
  sites:
    - url: http://cimus.biz
      name: Симус
    - url: https://exotic-zoo.ru
      name: ЭкзотикЗуу
    - url: https://nikoartgallery.com
      name: Галлерея