server:
  port: 8080
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/search_engine
    username: postgres
    password: 27030176

# example values

indexing-settings:
  sites:
    - url: http://www.playback.ru
      name: PLAYBACK
    - url: http://www.somthingexsht.ru
      name: Wrong
    - url: https://volochek.life
      name: LIFE
    - url: http://radiomv.ru
      name: RadioMV
    - url: https://ipfran.ru
      name: IPFran